apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-{re}
  namespace: trainticket
spec:
  mode: one
  duration: 10m
  selector:
    pods:
      trainticket:
        - {re-preserve-other}
        - {re-preserve}
        - {re-user}
        - {re-food}
        - {re-ticketinfo}
        - {re-security}
        - {re-contacts}
        - {re-travel}
        - {re-travel2}
        - {re-station}
        - {re-seat}
        - {re-order-other}
        - {re-order}
        - {re-assurance}
  stressors:
    cpu:
      workers: 2
      load: 25

