apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loss-{re}
  namespace: trainticket
spec:
  action: loss
  mode: one
  duration: 10m
  selector:
    pods:
      trainticket:
        - {re-preserve-other}
        - {re-preserve}
        - {re-user}
        - {re-food}
        - {re-ticketinfo}
        - {re-security}
        - {re-contacts}
        - {re-travel}
        - {re-travel2}
        - {re-station}
        - {re-seat}
        - {re-order-other}
        - {re-order}
        - {re-assurance}
  loss:
    loss: '20'
    correlation: '50'